#Travis jobs summary: 
# - 2 x86_64 jobs using gcc/clang
# - 1 windows job using visual studio 2017

language: c

arch:
  - amd64 #x86_64

dist: bionic

compiler:
  - gcc
  - clang

matrix:
  include:
    #Windows build amd64 Visual Studio
    - name: "Windows build Visual Studio"
      os: windows
      arch: amd64
      install:
        - choco install golang -y
      scripts:
        - export go=/c/Go/bin/go.exe
        - mkdir build
        - cd build
        - cmake -G "Visual Studio 15 2017 Win64" ..
        - /c/Program\ Files\ \(x86\)/Microsoft\ Visual\ Studio/2017/BuildTools/MSBuild/15.0/Bin/MSBuild.exe "ALL_BUILD.vcxproj" //p:Platform=x64 //p:Configuration=Release
        - cd ../test1/
        - chmod +x build.sh
        - ./build.sh
        - chmod +x run.sh
        - ./run.sh
        - cd $TRAVIS_BUILD_DIR
        - cd test2/ 
        - bash build.sh
        - bash run.sh

scripts: |-
  mkdir build
  cd build
  cmake ..
  make
  cd ../test1/
  bash build.sh
  bash run.sh
  cd $TRAVIS_BUILD_DIR
  cd test2 
  bash build.sh
  bash run.sh
